#记录日志
logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.crecode: TRACE
spring:
  jackson:
    date-format: yyyy-MM-dd #
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用数值timestamp表示日期
  datasource: #连接数据库
    dbcp2.validation-query: select 1
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crecode
    username: root
    password:
mybatis:
  mapper-Locations: classpath:cn/crecode/blog/mapper/*.xml #Mapper.xml
  type-Aliases-Package: cn.crecode.blog.pojo
  configuration:
    map-underscore-to-camel-case: true #数据库下划线转驼峰命名
server:
  port: 8443 #https加密端口号 443
  ssl:
    key-store: classpath:www.crecode.cn.jks  #SSL证书路径 一定要加上classpath:
    key-store-password: LWL980706 #SSL证书密码
    key-store-type: JKS #证书类型